### ISSUE TITLE
Varying types for `from` and `compilers` properties

### ISSUE THREAD

**Issue by zao** [archspec/archspec-json#1]
I'm currently reading in the JSON file in Rust with the help of `serde_json` and am having to do a fair bit of extra work to read the `from` and `compilers` part of microarchitecture objects.

This is due to that they are a bit varying type-wise, where `from` allows a literal `null`, a string, or a list of strings; and where `compilers` allows an object or a list of such objects.

Is there any particular historical, implementation, or usability reason as to why these are the way they are instead of say a list of string/object?

I can work around it with some effort, but I'm a bit curious as to how this came to be.

**Comment by tgamblin** [comment]
It would probably make other language implementations easier if we didn't allow variation in these.  I'm ok with changing it.  We vary types a fair bit in Spack YAML (mostly for readability for simple cases) but we don't have to do it in a formal document like the JSON file here.

**Comment by alalazo** [comment]
> Is there any particular historical, implementation, or usability reason as to why these are the way they are instead of say a list of string/object?

I'd say the historical reason is that this library was consumed by a dynamically typed language like Python, where treating these differences is trivial. I agree that accepting only a single type would make things easier in statically typed languages (e.g. in Go you can get by with only using struct tags).

**Comment by zao** [comment]
For anyone curious to the acrobatics needed, this is what I had to do:

For the one-or-many scenario I could similarly get away with having it try parsing each variant of an enum in turn: https://github.com/zao/archspec-rs/blob/30540ddc626cae4b569482dbdd40d2652c69c690/src/cpu/schema.rs#L42-L52

For the case that includes a null, it gets more gnarly: https://github.com/zao/archspec-rs/blob/30540ddc626cae4b569482dbdd40d2652c69c690/src/cpu/schema.rs#L94-L136
