### ISSUE TITLE
Move samples of /proc/cpuinfo in this repository?

### ISSUE THREAD

**Issue by alalazo** [archspec/archspec-json#13]
The idea around archspec is to keep in https://github.com/archspec/archspec-json all the static information that can be used by multiple implementations of the library in different programming languages. In our reference implementation in Python we store in the [tests](https://github.com/archspec/archspec/tree/master/tests/data/targets) folder samples of `/proc/cpuinfo` to be used in tests to ensure that detection works correctly.

I think it would be good to move this data in here so that it can be reused by other languages too.

**Comment by tgamblin** [comment]
yes! let's do it.

**Comment by boegel** [comment]
Agreed!
