### ISSUE TITLE
Intel oneapi and Nvidia NVHPC compilers

### ISSUE THREAD

**Issue by glennpj** [archspec/archspec-json#36]
Are there any plans to add the Intel OneAPI and Nvidia NVHPC compilers to archspec-json? If this is not in the works I can take a stab at it.

**Comment by glennpj** [comment]
I expect the oneapi entries to be very similar to the intel entries. Looking at the man page, some of the options for features, such as `-mfma`, `-mbmi`, `-mavx2`, and `-mlzcnt` can only be turned on via `-march=core-avx2`. That probably defeats the purpose of the `x86_64_v[2-4]` profiles, which I guess is why there are no entries for intel for those.

**Comment by alalazo** [comment]
@samcmill Would you, or anybody at NVIDIA be interested in tackling this issue?

**Comment by glennpj** [comment]
I guess I initiated this and then let it fall off of my radar. I will start working on the oneapi compilers.

**Comment by samcmill** [comment]
@cparrott73 is looking at the nvhpc compilers.

**Comment by cparrott73** [comment]
I have changes queued up to support the **nvhpc** compilers, but I am just awaiting for management approval before I can release them.  Hopefully very soon.

**Comment by glennpj** [comment]
I submitted #47 to cover the OneAPI part of this.

**Comment by cparrott73** [comment]
I have received management approval to contribute changes to support the nvhpc compilers to this project.  What's the best way to contribute this?  My changes consist of fairly straightforward modifications to the microarchitectures.json file.  I can produce a diff/patch if that would be preferable.

**Comment by boegel** [comment]
@cparrott73 A pull request to the `master` branch of this repository is easiest, since then the changes can be discussed in context easily if needed.

**Comment by cparrott73** [comment]
> @cparrott73 A pull request to the `master` branch of this repository is easiest, since then the changes can be discussed in context easily if needed.

Okay.  This was a bit of a learning curve for me, as I had never done this before.  I believe I just successfully sent the pull request with my changes.  Please take a look and let me know if you need anything else from me.  Thanks!

**Comment by glennpj** [comment]
This issue can be closed now that #67 is merged.
