### ISSUE TITLE
add support for AWS Graviton3

### ISSUE THREAD

**Issue by boegel** [archspec/archspec-json#39]
AWS `cg7` instances (Graviton3) are currently in preview, cfr. https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-ec2-c7g-instances-aws-graviton3-processors/.

I've asked preview access so we can see how to add support for correctly detecting these in archspec...

cc @ChristianKniep

**Comment by alalazo** [comment]
Feel free to ping me for a review of this as soon as a PR is ready.

**Comment by alalazo** [comment]
closed by #53
